### ISSUE TITLE
Python 3.4 requires modification of __init.py__ for DerApproximator

### ISSUE THREAD

**Issue by balasankarc** [PythonCharmers/OOSuite#1]
Hi,
When using Python 3.4, the command `from DerApproximator import *` fails with the following error

> >>> from DerApproximator import *
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.4/dist-packages/DerApproximator/**init**.py", line 3, in <module>
>     from DerApproximator import DerApproximatorException, get_d1, check_d1, get_d2
> ImportError: cannot import name 'DerApproximatorException'

But, this is solved by changing the line in __init.py__ to

from .DerApproximator import DerApproximatorException, get_d1, check_d1, get_d2

Notice the period infront of DerApproximator.

Is this a valid solution? If yes, please fix the source.

**Comment by ddskk123** [comment]
Thanks a lot for your advice, it works now!(almost moved to tears) ---2024.12.09
